---
version: "3.7"
services:
  ts-nginx-test:
    image: tailscale/tailscale:latest
    container_name: ts-nginx-test
    hostname: nginx-test
    #environment:
      #- TS_AUTHKEY=tskey-client-kZye2b2CNTRL-C7hZoFwYhYEKApKDtt3BYEsA4UJAtawk
      #- TS_EXTRA_ARGS=--advertise-tags=tag:container
      #- TS_STATE_DIR=/var/lib/tailscale
    volumes:
      #- ${PWD}/ts-nginx-test/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  nginx-pid-test1:
    image: nginx
    container_name: nginx-pid-test1
    network_mode: service:ts-nginx-test
